In [1]:
import numpy as np

In [2]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
def info_array(a):
    print("Dimension:",a.ndim)
    print("shape:",a.shape)
    print("size(number of element):",a.size)
    print("Datatype;",a.dtype)

In [11]:
info_array(arr1)

Dimension: 1
shape: (12,)
size(number of element): 12
Datatype; int32


### Numpy Notes
* arange : to create the range of element -np.arange(start,end.step)
* linspace - to create the range of element with number of element this will calculate step size by its own, it will also 
include start value & end value - np.linspace(start,end,number of element)
* 3) reshape -

In [16]:
arr3 = np.linspace(10,45,6)
arr3

array([10., 17., 24., 31., 38., 45.])

In [19]:
arr4 = np.linspace(1,9,4)
arr4

array([1.        , 3.66666667, 6.33333333, 9.        ])

In [20]:
arr5 = np.linspace(1,5,125)
arr5

array([1.        , 1.03225806, 1.06451613, 1.09677419, 1.12903226,
       1.16129032, 1.19354839, 1.22580645, 1.25806452, 1.29032258,
       1.32258065, 1.35483871, 1.38709677, 1.41935484, 1.4516129 ,
       1.48387097, 1.51612903, 1.5483871 , 1.58064516, 1.61290323,
       1.64516129, 1.67741935, 1.70967742, 1.74193548, 1.77419355,
       1.80645161, 1.83870968, 1.87096774, 1.90322581, 1.93548387,
       1.96774194, 2.        , 2.03225806, 2.06451613, 2.09677419,
       2.12903226, 2.16129032, 2.19354839, 2.22580645, 2.25806452,
       2.29032258, 2.32258065, 2.35483871, 2.38709677, 2.41935484,
       2.4516129 , 2.48387097, 2.51612903, 2.5483871 , 2.58064516,
       2.61290323, 2.64516129, 2.67741935, 2.70967742, 2.74193548,
       2.77419355, 2.80645161, 2.83870968, 2.87096774, 2.90322581,
       2.93548387, 2.96774194, 3.        , 3.03225806, 3.06451613,
       3.09677419, 3.12903226, 3.16129032, 3.19354839, 3.22580645,
       3.25806452, 3.29032258, 3.32258065, 3.35483871, 3.38709

In [21]:
info_array(arr5)

Dimension: 1
shape: (125,)
size(number of element): 125
Datatype; float64


In [27]:
arr6 = np.linspace(1,24,24 ,dtype ='int')
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [28]:
arr6.shape

(24,)

In [29]:
arr6.reshape(4,6)   # this operation are not save in this operation only see the output.

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [30]:
arr6.shape

(24,)

In [31]:
# assignement : reshape above array



In [36]:
arr6.reshape(3,4,2)


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

##### Convert 2D to 1D

In [37]:
arr6 = arr6.reshape(6,4)
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [38]:
arr6.ravel('C') #  c programmong ## convert 2 D to 1D - row basis

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [39]:
arr6.ravel("F")  # FORTRON 77 programing - column basis  - 2D to 1D

array([ 1,  5,  9, 13, 17, 21,  2,  6, 10, 14, 18, 22,  3,  7, 11, 15, 19,
       23,  4,  8, 12, 16, 20, 24])

#### resize : change the size of array 

In [40]:
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [41]:
arr6.resize(3,8)
arr6

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [42]:
np.resize(arr6,(7,5)) # resize the element with any size or differnt range.

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24,  1],
       [ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

### Concatenate -

In [43]:
arr8 = np.arange(1,7).reshape(2,3)
arr8

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr9 = np.arange(7,13).reshape(2,3)
arr9

array([[ 7,  8,  9],
       [10, 11, 12]])

In [45]:
np.concatenate([arr8,arr9]) # by default row wise - axis =0

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
np.concatenate([arr8,arr9],axis =1)   # column wise


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [47]:
arr10 = np.arange(13,19).reshape(3,2)
arr10

array([[13, 14],
       [15, 16],
       [17, 18]])

In [50]:
#np.concatenate([arr8,arr10])  # we have same dimension arrays to join

In [51]:
#np.concatenate([arr8,arr10],axis =1)

#### hstack : Horizontal stack - column join
* used to stack the array

In [52]:
np.hstack([arr8,arr9])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

#### vstack - verstical array - row join

In [53]:
np.vstack([arr8,arr9])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### repeat -


In [55]:
arr11 = np.arange(3)
arr11

array([0, 1, 2])

In [56]:
arr11.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [57]:
arr11.repeat(23)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2])

In [59]:
arr11.repeat([3,15,11]) # 0-3,1-15,2-11

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2])

####  Identity matrix -np.eye()

In [60]:
np.eye(3,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.]])

In [61]:
np.eye(3,7,4)

array([[0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [62]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## split  -
 * split function is used to split the numpy array into multiple arrays

In [66]:
arr6 

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [67]:
np.split(arr6,(1,2))

[array([[1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16]]),
 array([[17, 18, 19, 20, 21, 22, 23, 24]])]

In [71]:
arr12 = np.linspace(1,100,100, dtype ="int").reshape(10,10)
arr12

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [73]:
np.split(arr12,(3,6))

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]),
 array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]]),
 array([[ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])]

In [76]:
np.split(arr12,[2,4,6,8])

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]),
 array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]]),
 array([[41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]]),
 array([[61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
        [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]]),
 array([[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])]

In [77]:
np.split(arr12,[2,4,6,8], axis =1)

[array([[ 1,  2],
        [11, 12],
        [21, 22],
        [31, 32],
        [41, 42],
        [51, 52],
        [61, 62],
        [71, 72],
        [81, 82],
        [91, 92]]),
 array([[ 3,  4],
        [13, 14],
        [23, 24],
        [33, 34],
        [43, 44],
        [53, 54],
        [63, 64],
        [73, 74],
        [83, 84],
        [93, 94]]),
 array([[ 5,  6],
        [15, 16],
        [25, 26],
        [35, 36],
        [45, 46],
        [55, 56],
        [65, 66],
        [75, 76],
        [85, 86],
        [95, 96]]),
 array([[ 7,  8],
        [17, 18],
        [27, 28],
        [37, 38],
        [47, 48],
        [57, 58],
        [67, 68],
        [77, 78],
        [87, 88],
        [97, 98]]),
 array([[  9,  10],
        [ 19,  20],
        [ 29,  30],
        [ 39,  40],
        [ 49,  50],
        [ 59,  60],
        [ 69,  70],
        [ 79,  80],
        [ 89,  90],
        [ 99, 100]])]

In [80]:
sp1, sp2, sp3 = np.split(arr12,[4,7],axis =1)

In [81]:
sp1

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44],
       [51, 52, 53, 54],
       [61, 62, 63, 64],
       [71, 72, 73, 74],
       [81, 82, 83, 84],
       [91, 92, 93, 94]])

In [82]:
sp2

array([[ 5,  6,  7],
       [15, 16, 17],
       [25, 26, 27],
       [35, 36, 37],
       [45, 46, 47],
       [55, 56, 57],
       [65, 66, 67],
       [75, 76, 77],
       [85, 86, 87],
       [95, 96, 97]])

In [83]:
sp3

array([[  8,   9,  10],
       [ 18,  19,  20],
       [ 28,  29,  30],
       [ 38,  39,  40],
       [ 48,  49,  50],
       [ 58,  59,  60],
       [ 68,  69,  70],
       [ 78,  79,  80],
       [ 88,  89,  90],
       [ 98,  99, 100]])